
name: GitHub Actions lint
on:
  workflow_call:
  push:
  pull_request:

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.3
      - name: Check workflow files
        uses: docker://rhysd/actionlint:latest
        with:
          args: -color
