name: "Gradle Release"

on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: number

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Release
    if: github.event.created
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.RELEASE_APP_ID }}
          private-key: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}
      - name: Checkout Branch
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
      - name: Set Version
        run: |
          echo "version=$(echo ${{ github.ref }} | sed 's/refs\/heads\/release\///')" >> "$GITHUB_ENV"
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ inputs.java-version }}
          cache: "gradle"          
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v3
      - name: Bump Version
        uses: gradle/gradle-build-action@v3
        with:
          arguments: bumpVersion -PnewVersion=${{ env.version }}
      - name: Configure Git Author
        run: |
          git config user.name "GitHub Actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Commit and Push Changes
        run: |
          git commit -am "Bump version to ${{ env.version }}"
          git tag -a v${{ env.version }} -m "Release version ${{ env.version }}"
          git push -u origin release/${{ env.version }} --follow-tags
      - name: Create Pull Request
        run: gh pr create -B master --title 'Release version ${{ env.version }}' --body 'This pull request bumps the version to ${{ env.version }}'
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
