name: 'Gradle Publish'

on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: number
  
permissions:
  contents: write

jobs:
  publish:
    name: Publish
    if: contains(github.head_ref, 'releases/') && github.event.pull_request.merged == true && github.base_ref == 'master'
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ inputs.java-version }}
          cache: 'gradle'
      - name: Checkout Branch
        uses: actions/checkout@v4.1.5
      - name: Get the version
        id: get_version
        run: echo "version=$(git describe --tags --abbrev=0)" >> "$GITHUB_OUTPUT"
      - name: Create GitHub Release
        run: gh release create ${{ steps.get_version.outputs.version }} --verify-tag --title ${{ steps.get_version.outputs.version }} --notes "Release version ${{ steps.get_version.outputs.version }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v3
      - name: Publish package
        uses: gradle/gradle-build-action@v3
        with:
          arguments: publishToSonatype
        env:
          ORG_GRADLE_PROJECT_SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
