name: 'Gradle Build'

on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: number

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.5
        with:
          ref: ${{ github.event.client_payload.ref }}
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ inputs.java-version }}
          cache: 'gradle'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v3
      - name: Build
        uses: gradle/gradle-build-action@v3
        with:
          arguments: build
      - uses: codecov/codecov-action@v4
        with:
          verbose: true
